import type {
  MappingStore,
  MappingEntry,
  ScopeSummary,
  RequestLogEntry,
  SessionSummary,
  DashboardStats,
  DsiStats,
  LeakReport,
} from "./mapping-store";

/**
 * In-memory implementation of MappingStore for testing purposes only.
 * Does not persist data between runs.
 */
export class InMemoryMappingStore implements MappingStore {
  private mappings = new Map<string, MappingEntry[]>();
  private requestLogs: RequestLogEntry[] = [];
  private requestLogIdCounter = 0;

  initialize(): void {
    // No-op for in-memory store
  }

  listMappings(scopeId: string): MappingEntry[] {
    return this.mappings.get(scopeId) || [];
  }

  upsertMappings(
    scopeId: string,
    entries: Array<Pick<MappingEntry, "kind" | "originalValue" | "pseudonym">>
  ): void {
    const existingMappings = this.mappings.get(scopeId) || [];
    const existingSet = new Set(
      existingMappings.map((m) => `${m.kind}|${m.originalValue}|${m.pseudonym}`)
    );

    for (const entry of entries) {
      const key = `${entry.kind}|${entry.originalValue}|${entry.pseudonym}`;
      if (existingSet.has(key)) continue;

      existingMappings.push({
        scopeId,
        kind: entry.kind,
        originalValue: entry.originalValue,
        pseudonym: entry.pseudonym,
        createdAt: new Date().toISOString(),
      });
      existingSet.add(key);
    }

    this.mappings.set(scopeId, existingMappings);
  }

  listScopes(): ScopeSummary[] {
    const scopes: ScopeSummary[] = [];
    for (const [scopeId, entries] of this.mappings) {
      scopes.push({
        scopeId,
        entryCount: entries.length,
        lastCreatedAt: entries[entries.length - 1]?.createdAt || new Date().toISOString(),
      });
    }
    return scopes;
  }

  listRecentMappings(limit: number): MappingEntry[] {
    const allMappings: MappingEntry[] = [];
    for (const entries of this.mappings.values()) {
      allMappings.push(...entries);
    }
    return allMappings.slice(-limit);
  }

  insertRequestLog(
    entry: Omit<RequestLogEntry, "id" | "createdAt" | "responseBody">
  ): number {
    const id = ++this.requestLogIdCounter;
    this.requestLogs.push({
      id,
      ...entry,
      responseBody: null,
      createdAt: new Date().toISOString(),
    });
    return id;
  }

  updateResponseBody(logId: number, responseBody: string): void {
    const log = this.requestLogs.find((l) => l.id === logId);
    if (log) {
      log.responseBody = responseBody;
    }
  }

  listRequestLogs(limit: number): RequestLogEntry[] {
    return this.requestLogs.slice(-limit);
  }

  getRequestLog(id: number): RequestLogEntry | null {
    return this.requestLogs.find((l) => l.id === id) || null;
  }

  getStats(): DashboardStats {
    // Minimal implementation for testing
    return {
      totalMappings: Array.from(this.mappings.values()).flat().length,
      totalRequests: this.requestLogs.length,
      totalTransforms: this.requestLogs.reduce((sum, log) => sum + log.transformedCount, 0),
      mappingsByKind: {},
      requestsByEndpoint: {},
      recentActivity: [],
      topTokens: [],
    };
  }

  listSessions(limit: number): SessionSummary[] {
    return [];
  }

  listRequestLogsByTraceId(traceId: string): RequestLogEntry[] {
    return this.requestLogs.filter((log) => log.traceId === traceId);
  }

  getDsiStats(): DsiStats {
    return {
      totalRequests: this.requestLogs.length,
      totalTransforms: this.requestLogs.reduce((sum, log) => sum + log.transformedCount, 0),
      totalEntities: Array.from(this.mappings.values()).flat().length,
      entitiesByKind: {},
      requestsByDay: [],
      requestsByModel: {},
      requestsByEndpoint: {},
      avgTransformsPerRequest: 0,
      sessions: 0,
      sampleMappings: [],
    };
  }

  scanLeaks(limit?: number, shieldTerms?: string[]): LeakReport {
    return {
      totalRequestsScanned: 0,
      requestLeaks: 0,
      responseLeaks: 0,
      shieldLeaks: 0,
      leakDetails: [],
    };
  }

  scanLeaksCached(shieldTerms?: string[]): LeakReport {
    return this.scanLeaks(undefined, shieldTerms);
  }

  getSessionTitle(traceId: string): string | null {
    return null;
  }

  upsertSessionTitle(traceId: string, title: string, isAutoGenerated: boolean): void {
    // No-op
  }

  deleteSession(traceId: string): void {
    // No-op
  }
}
