export type MappingKind = "org" | "svc" | "tbl" | "col" | "idn" | "per" | "url" | "email" | "phone";

export type MappingEntry = {
  scopeId: string;
  kind: MappingKind;
  originalValue: string;
  pseudonym: string;
  createdAt: string;
};

export type ScopeSummary = {
  scopeId: string;
  entryCount: number;
  lastCreatedAt: string;
};

export type RequestLogEntry = {
  id: number;
  traceId: string;
  requestId: string;
  endpoint: string;
  model: string | null;
  originalBody: string;
  rewrittenBody: string;
  responseBody: string | null;
  transformedCount: number;
  createdAt: string;
};

export type SessionSummary = {
  traceId: string;
  title: string;
  requestCount: number;
  totalTransforms: number;
  models: string[];
  firstRequestAt: string;
  lastRequestAt: string;
  previewMessage: string | null;
};

export type DashboardStats = {
  totalMappings: number;
  totalRequests: number;
  totalTransforms: number;
  mappingsByKind: Record<string, number>;
  requestsByEndpoint: Record<string, number>;
  recentActivity: Array<{ date: string; count: number }>;
  topTokens: Array<{ originalValue: string; pseudonym: string; kind: string; occurrences: number }>;
};

export type LeakContext = {
  value: string;
  pseudonym?: string;
  originalValue?: string;
  context: string;
  position: number;
  bodyType: "request" | "response";
};

export type LeakDetail = {
  requestId: string;
  traceId: string;
  endpoint: string;
  createdAt: string;
  leakedOriginals: LeakContext[];
  leakedPseudonyms: LeakContext[];
  leakedShieldTerms: LeakContext[];
};

export type LeakReport = {
  totalRequestsScanned: number;
  requestLeaks: number;
  responseLeaks: number;
  shieldLeaks: number;
  leakDetails: LeakDetail[];
};

export type DsiStats = {
  totalRequests: number;
  totalTransforms: number;
  totalEntities: number;
  entitiesByKind: Record<string, number>;
  requestsByDay: Array<{ date: string; count: number }>;
  requestsByModel: Record<string, number>;
  requestsByEndpoint: Record<string, number>;
  avgTransformsPerRequest: number;
  sessions: number;
  sampleMappings: Array<{ kind: string; original: string; pseudonym: string }>;
};

export interface MappingStore {
  initialize(): void;
  listMappings(scopeId: string): MappingEntry[];
  upsertMappings(scopeId: string, entries: Array<Pick<MappingEntry, "kind" | "originalValue" | "pseudonym">>): void;
  listScopes(): ScopeSummary[];
  listRecentMappings(limit: number): MappingEntry[];
  insertRequestLog(entry: Omit<RequestLogEntry, "id" | "createdAt" | "responseBody">): number;
  updateResponseBody(logId: number, responseBody: string): void;
  listRequestLogs(limit: number): RequestLogEntry[];
  getRequestLog(id: number): RequestLogEntry | null;
  getStats(): DashboardStats;
  listSessions(limit: number): SessionSummary[];
  listRequestLogsByTraceId(traceId: string): RequestLogEntry[];
  getDsiStats(): DsiStats;
  scanLeaks(limit?: number, shieldTerms?: string[]): LeakReport;
  scanLeaksCached(shieldTerms?: string[]): LeakReport;
  getSessionTitle(traceId: string): string | null;
  upsertSessionTitle(traceId: string, title: string, isAutoGenerated: boolean): void;
  deleteSession(traceId: string): void;
}
