export type MappingKind = "org" | "svc" | "tbl" | "col" | "idn" | "per" | "url" | "email" | "phone";

export type MappingEntry = {
  scopeId: string;
  kind: MappingKind;
  originalValue: string;
  pseudonym: string;
  createdAt: string;
};

export type ScopeSummary = {
  scopeId: string;
  entryCount: number;
  lastCreatedAt: string;
};

export type RequestLogEntry = {
  id: number;
  traceId: string;
  requestId: string;
  endpoint: string;
  model: string | null;
  originalBody: string;
  rewrittenBody: string;
  responseBody: string | null;
  transformedCount: number;
  createdAt: string;
};

export type SessionSummary = {
  traceId: string;
  title: string;
  requestCount: number;
  totalTransforms: number;
  models: string[];
  firstRequestAt: string;
  lastRequestAt: string;
  previewMessage: string | null;
};

export type DashboardStats = {
  totalMappings: number;
  totalRequests: number;
  totalTransforms: number;
  mappingsByKind: Record<string, number>;
  requestsByEndpoint: Record<string, number>;
  recentActivity: Array<{ date: string; count: number }>;
  topTokens: Array<{ originalValue: string; pseudonym: string; kind: string; occurrences: number }>;
};

export type LeakContext = {
  value: string;
  pseudonym?: string;
  originalValue?: string;
  context: string;
  position: number;
  bodyType: "request" | "response";
};

export type LeakDetail = {
  requestId: string;
  traceId: string;
  endpoint: string;
  createdAt: string;
  leakedOriginals: LeakContext[];
  leakedPseudonyms: LeakContext[];
  leakedShieldTerms: LeakContext[];
};

export type LeakReport = {
  totalRequestsScanned: number;
  requestLeaks: number;
  responseLeaks: number;
  shieldLeaks: number;
  leakDetails: LeakDetail[];
};

export type DsiStats = {
  totalRequests: number;
  totalTransforms: number;
  totalEntities: number;
  entitiesByKind: Record<string, number>;
  requestsByDay: Array<{ date: string; count: number }>;
  requestsByModel: Record<string, number>;
  requestsByEndpoint: Record<string, number>;
  avgTransformsPerRequest: number;
  sessions: number;
  sampleMappings: Array<{ kind: string; original: string; pseudonym: string }>;
};

// ── GDPR Types ────────────────────────────────────────────────────────────────

/** A masking operation audit entry derived from request_log. */
export type AuditLogEntry = {
  id: number;
  timestamp: string;
  maskedCount: number;
  strategy: string;   // endpoint kind, e.g. "chat-completions"
  provider: string;   // model name
  categories: string[]; // entity kinds detected in the session
};

/** Filters for querying audit logs. */
export type AuditLogQuery = {
  page?: number;
  pageSize?: number;
  dateFrom?: string;
  dateTo?: string;
  strategy?: string;
  provider?: string;
};

/** Paginated audit log response. */
export type AuditLogPage = {
  entries: AuditLogEntry[];
  total: number;
  page: number;
  pageSize: number;
};

/** A GDPR event record (erasure, export, retention cleanup). */
export type GdprEvent = {
  id: number;
  timestamp: string;
  eventType: "erasure" | "export" | "retention_cleanup";
  affectedCount: number;
  searchTerm?: string;
  details: string;
};

/** Result of a right-to-erasure operation. */
export type EraseResult = {
  deletedMappings: number;
  deletedRequests: number;
  deletedSessions: number;
};

/** Result of a data retention cleanup. */
export type RetentionResult = {
  deletedMappings: number;
  deletedRequests: number;
  deletedSessions: number;
  cutoffDate: string;
};

/** Exported data bundle for GDPR Article 20 portability. */
export type ExportData = {
  exportedAt: string;
  retentionDays: number;
  mappingCount: number;
  requestCount: number;
  mappings: MappingEntry[];
  requests: Array<Pick<RequestLogEntry, "id" | "traceId" | "requestId" | "endpoint" | "model" | "transformedCount" | "createdAt">>;
  gdprEvents: GdprEvent[];
};

export interface MappingStore {
  initialize(): void;
  listMappings(scopeId: string): MappingEntry[];
  upsertMappings(scopeId: string, entries: Array<Pick<MappingEntry, "kind" | "originalValue" | "pseudonym">>): void;
  listScopes(): ScopeSummary[];
  listRecentMappings(limit: number): MappingEntry[];
  insertRequestLog(entry: Omit<RequestLogEntry, "id" | "createdAt" | "responseBody">): number;
  updateResponseBody(logId: number, responseBody: string): void;
  listRequestLogs(limit: number): RequestLogEntry[];
  getRequestLog(id: number): RequestLogEntry | null;
  getStats(): DashboardStats;
  listSessions(limit: number): SessionSummary[];
  listRequestLogsByTraceId(traceId: string): RequestLogEntry[];
  getDsiStats(): DsiStats;
  scanLeaks(limit?: number, shieldTerms?: string[]): LeakReport;
  scanLeaksCached(shieldTerms?: string[]): LeakReport;
  getSessionTitle(traceId: string): string | null;
  upsertSessionTitle(traceId: string, title: string, isAutoGenerated: boolean): void;
  deleteSession(traceId: string): void;

  // ── GDPR ──────────────────────────────────────────────────────────────────
  queryAuditLogs(query: AuditLogQuery): AuditLogPage;
  insertGdprEvent(event: Omit<GdprEvent, "id" | "timestamp">): void;
  listGdprEvents(limit?: number): GdprEvent[];
  deleteOlderThan(days: number): RetentionResult;
  eraseBySearchTerm(term: string): EraseResult;
  exportAll(retentionDays: number): ExportData;
}
